#!/bin/bash

# .bashrc file
# Author: Zheng Hao Tan <tanzhao@umich.edu>
# MIT License

# These are my bashrc settings. Feel free to take whatever you want.

BLUE_BOLD='\[\e[01;34m\]'
RED_BOLD='\[\e[01;31m\]'
WHITE_BOLD='\[\e[01;0m\]'
PS1="${RED_BOLD}\u@\h ${BLUE_BOLD}\$PWD${WHITE_BOLD} \$ "

# Ignore case during tab completion.
bind 'set completion-ignore-case on'

export PATH="$PATH:/home/armx/.local/bin:/armx/run"
