#!/bin/zsh

path+=$PWD/dockerfiles/ide
path+=$PWD/dockerfiles/android-re
path+=$PWD/dockerfiles/pwn
path+=$PWD/dockerfiles/web-pwn
path+=$PWD/dockerfiles/web-dev
path+=$PWD/dockerfiles/arm-x

cd workspace
