version: "3"

services:
    arm-box:
        build:
            context: .
            dockerfile: ./arm.dockerfile
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        networks:
            default:
                aliases:
                    - arm-box
    pwn-box:
        build:
            context: .
            dockerfile: ./x86.dockerfile
        cap_add:
            - SYS_PTRACE
        security_opt:
            - seccomp:unconfined
        networks:
            default:
                aliases:
                    - pwnbox

networks:
    default:
        driver: bridge
