#!/bin/zsh

thisdir=${0:a:h}

container_name=$(docker-compose -f $thisdir/docker-compose.yaml run -d -v "`pwd`":/home/dev/workspace gdbserver)
container_name=$(echo $container_name | grep gdbserver)

echo
echo Attach to gdbserver by executing:
echo docker exec -it $container_name /bin/bash
echo

docker-compose -f $thisdir/docker-compose.yaml run -v "`pwd`":/home/dev/workspace arm-box

echo
echo Killing gdbserver: $container_name
echo $container_name | xargs docker kill 2>&1 > /dev/null
